version: "3"

services:
  milan:
    hostname: milan
    user: 1000:1000

    build:
      context: ./
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    volumes:
      - ./:/app

    working_dir: "/app"
    command: "bash"
