version: "3"

services:
  milan:
    build:
      context: .

    shm_size: 1gb
    user: milan
    hostname: milan
    working_dir: /app

    volumes:
      - ./:/app
      - ./milan:/milan/milan
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
        - DISPLAY=${DISPLAY}

    command: /bin/bash
