site_name: Milan
repo_url: https://github.com/fscherf/milan
copyright: Copyright &copy; 2023 Florian Scherf

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:

    # light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo

      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - content.code.copy

plugins:
  - search
  - mkdocstrings
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - Usage: usage.md
