name: ci


on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y
        pip install --upgrade setuptools tox
        pip install .[test]
        python -m playwright install-deps
        python -m playwright install

    - name: Run Tox
      env:
        MILAN_CI_TEST: 1
      run: tox -e py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml

    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: python-${{ matrix.python-version }}-artifacts
        path: tests/artifacts
