name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["py38", "py39", "py310", "py311", "py312"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t app .

    - name: Run pytest inside Docker container
      run: |
        docker run \
          -v ./:/app \
          -w /app \
          -u root \
          -e MILAN_CI_TEST=1 \
          app:latest \
          tox -e ${{ matrix.python-version }}

    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.python-version }}-artifacts
        path: artifacts

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
