name: "PyPi: Release"

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_NAME: milan

jobs:
  pypi-release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PROJECT_NAME }}

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
